### ISSUE TITLE
Error when opening Sublime Text 2 - Dateformat

### ISSUE THREAD

**Issue by chaelli** [dennishall/Sublime-Text-Subversion-plug-in#5]
When opening sublime text 2 with installed subversion I get the following error:
2012-04-10 13:34:10
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 587, in run
  File "./sublimesvn/status.py", line 432, in fetch_branches
  File "./sublimesvn/status.py", line 412, in parse_ls_line
  File "._strptime.py", line 325, in _strptime
ValueError: time data '2011 Okt 04 00:00' does not match format '%Y %b %d %H:%M'
2012-04-10 13:34:32
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 587, in run
  File "./sublimesvn/status.py", line 432, in fetch_branches
  File "./sublimesvn/status.py", line 412, in parse_ls_line
  File "._strptime.py", line 325, in _strptime
ValueError: time data '2011 Okt 04 00:00' does not match format '%Y %b %d %H:%M'

**Comment by flatstadt** [comment]
Same here:

2012-04-28 21:58:07
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 938, in run
  File "./sublimesvn/status.py", line 354, in fetch
  File "./sublimesvn/proc.py", line 385, in is_version
  File "./sublimesvn/proc.py", line 384, in norm
ValueError: invalid literal for int() with base 10: ''
2012-04-30 09:55:23
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 938, in run
  File "./sublimesvn/status.py", line 354, in fetch
  File "./sublimesvn/proc.py", line 385, in is_version
  File "./sublimesvn/proc.py", line 384, in norm
ValueError: invalid literal for int() with base 10: ''

**Comment by alvaroveliz** [comment]
I got the same error:
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 938, in run
  File "./sublimesvn/status.py", line 354, in fetch
  File "./sublimesvn/proc.py", line 385, in is_version
  File "./sublimesvn/proc.py", line 384, in norm

**Comment by hugodotlau** [comment]
i got the same @ubuntu 11.11 :
2012-05-15 14:24:40
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 959, in run
  File "./sublimesvn/status.py", line 320, in fetch
  File "./sublimesvn/monitor.py", line 59, in monitor
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/api.py", line 333, in schedule
    timeout=self.timeout)
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/inotify.py", line 741, in **init**
    self._inotify = Inotify(watch.path, watch.is_recursive)
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/inotify.py", line 449, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/inotify.py", line 629, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/inotify.py", line 645, in _add_watch
    Inotify._raise_error()
  File "/home/myhome/.config/sublime-text-2/Packages/SVN/lib/all/watchdog/observers/inotify.py", line 681, in _raise_error
    raise OSError(os.strerror(_errnum))
OSError: Permission denied

**Comment by lgaticaq** [comment]
SO Ubuntu 12.04 Sublime Text v2.0.1 build 2217

2012-07-30 10:25:48
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 989, in run
  File "./sublimesvn/status.py", line 849, in fetch_branches
  File "./sublimesvn/status.py", line 805, in parse_ls_line
KeyError: u'09'

**Comment by fdl19881** [comment]
i got the same error on windows 7 , sublime text 2.0.2 build 2221.

**Comment by fdl19881** [comment]
like this.
2013-09-26 14:55:31
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/proc.py", line 97, in run
ProcessError
2013-09-26 14:55:38
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/proc.py", line 97, in run
ProcessError: Active code page: 65001
